##  SVD

* This method allows you to get complete S, U, V

In [ ]:
import numpy as np
from numpy.linalg import svd

In [ ]:
# this matrix has rank=2, since col3 = col1+co2, 
## but col1 and col2 are independent from each other

A = np.array([[1,2,3], [4,5,6], [5,7,9]])

U, S, VT = svd(A)

In [ ]:
print("Left Singular Vectors:")
print(U)
print("Singular Values:") 
print(np.diag(S))
print("Right Singular Vectors:") 
print(VT)

Left Singular Vectors:
[[-0.2354116   0.78182354 -0.57735027]
 [-0.55937325 -0.5947842  -0.57735027]
 [-0.79478485  0.18703934  0.57735027]]
Singular Values:
[[1.56633231e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.12593979e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.17807579e-15]]
Right Singular Vectors:
[[-0.41158755 -0.56381288 -0.71603821]
 [-0.8148184  -0.12429146  0.56623547]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
# Return the original matrix A
# @ is used for matrix multiplication in Py3, use np.matmul with Py2
print(U @ np.diag(S) @ VT)

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 7. 9.]]


##  SVD

* Sklearn Truncated SVD - This is used for dimensional reduction directly

In [ ]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [ ]:
A = np.array([[1,2,3], [4,5,6], [5,7,9]])
print("Original Matrix:")
A

Original Matrix:


array([[1, 2, 3],
       [4, 5, 6],
       [5, 7, 9]])

In [ ]:
svd =  TruncatedSVD(n_components = 2)  # reduce to 2 features
A_transf = svd.fit_transform(A)

print("Singular values:")
print(svd.singular_values_)
print()

print("Transformed Matrix after reducing to 2 features:")
print(A_transf)

Singular values:
[15.66332312  0.81259398]

Transformed Matrix after reducing to 2 features:
[[ 3.68732795  0.6353051 ]
 [ 8.76164389 -0.48331806]
 [12.44897184  0.15198704]]
